server:
  port: 8083
minio:
  endpoint: http://localhost:9000
  access-key: your-access-key
  secret-key: your-secret-key
  bucket: complaints
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/support-service